server:
 port: 8899
spring:
 application:
    name: CONFIG-SERVER
 cloud:
   config:
      server:
        git:
          uri: https://github.com/nihal2608/config-server.git
          clone-on-start: true
   
